# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: iap-agent-registry-agent-iam-binding
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: IAP Agent Registry Agent IAM Binding
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-iap-policy.git
      sourceType: git
      dir: /modules/iap-agent-registry-agent-iam-binding
    version: 0.0.3
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which the resource belongs.
        varType: string
      - name: location
        description: The location of the resource.
        varType: string
      - name: agent_id
        description: The ID of the Agent Registry agent.
        varType: string
        required: true
        connections:
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-agent
              version: ">=0.0.14"
            spec:
              outputExpr: agent_id
      - name: role
        description: The role that should be applied. E.g., roles/iap.egressor.
        varType: string
        required: true
      - name: members
        description: Identities that will be granted the privilege in the role.
        varType: list(string)
        required: true
      - name: condition
        description: An optional IAM Condition for the binding.
        varType: |-
          object({
              title       = string
              description = optional(string)
              expression  = string
            })
    outputs:
      - name: etag
        description: The etag of the IAM binding.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google-nightly
        version: 2026.3.26-7.25.0
