# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: iap_web_iam_binding-iap-web-iam-binding
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: IAP Web IAM Binding
    source:
      repo: https://github.com/Daisyprakash/terraform-google-iap-policy.git
      sourceType: git
      dir: /modules/iap-web-iam-binding
    version: 0.0.3
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: iap_web_iam_binding
        location: examples/iap_web_iam_binding
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which the resource belongs.
        varType: string
        required: true
      - name: role
        description: The role that should be applied. E.g., roles/iap.httpsResourceAccessor
        varType: string
        required: true
      - name: members
        description: Identities that will be granted the privilege in the role.
        varType: list(string)
        required: true
      - name: condition
        description: An optional IAM Condition for the binding.
        varType: |-
          object({
              title       = string
              description = optional(string)
              expression  = string
            })
    outputs:
      - name: iap_web_iam_binding_etag
        description: The etag of the IAM policy.
      - name: iap_web_iam_binding_id
        description: The identifier of the IAM binding resource.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/iap.admin 
          - roles/browser 
    services:
      - iap.googleapis.com
      - cloudresourcemanager.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.53, < 8"
