# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: iap_web_iam_binding-iap-web-iam-binding-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: IAP Web IAM Binding
    source:
      repo: /modules/iap_web_iam_binding
      dir: /modules/iap-web-iam-binding
  ui:
    input:
      variables:
        bucket_name:
          name: bucket_name
          title: Bucket Name
        condition:
          name: condition
          title: Condition
        members:
          name: members
          title: Members
        project_id:
          name: project_id
          title: Project Id
        role:
          name: role
          title: Role
